### ISSUE TITLE
Font family ve stillendirme hakkında

### ISSUE THREAD

**Issue by Ardakilic** [acikkaynak/acikkaynak-website#14]
acikkaynak.info adresinde paragraf içi fontu ile, projeler sekmesindeki fontlara el atılsa sanki daha güzel olacak. Geniş ekranda akınca ufak bir de metinlerde kullanılan font bence değiştirilebilir. Front-end, ux bilgisi olan arkadaşlar da yorumlarsa sevinirim.

**Comment by eserozvataf** [comment]
Özellikle CSS framework'e karar verdikten sonra belki stillendirme ile ilgili de @Ardakilic 'ın açtığı tartışmayı devam ettirmemiz gerekecek.

**Comment by eserozvataf** [comment]
Aslında hem Semantic UI React kullanımı hem de Figma/XD üzerinden iletilen tasarımlarla bir "tasarım dili" oluşuyor ve bu çalışmalara feedback vererek font ve stillendirme konularını da işliyor/değerlendiriyor oluyoruz. Dolayısıyla bu issue'yu kapatıp tasarım dili review'larına devredelim konuyu.
