### ISSUE TITLE
Açık Kaynak 1.0 Projelendirme

### ISSUE THREAD

**Issue by eserozvataf** [acikkaynak/acikkaynak-website#17]
Merhaba,

"Açık Kaynak" için yola çıkarken hedefler oldukça büyüktü, Türkiye'deki açık kaynak ekosisteminin lokomotifi olmak, insanları açık kaynak geliştirmeye motive etmek, farkındalık yaratmak ve engelleri ortadan kaldırmak gibi bolca görev üstlenebileceğimiz bir alanımız mevcuttu.

Nasıl, nereden, ne kadar küçük adımlarla başlarsak başlayalım bir noktadaki eksikliği gidermiş olacaktık. Ve en ufaktan başladık. Önce GitHub'ın kendi kaynakları ile Türkiye'deki ve Türkçe konuşan geliştiricilerin açık kaynak proje indeksi görevi gördük. Ama halen bunun sosyal tarafıyla ilgili yapacak çok işimiz vardı.

Şimdi bir adım daha atıyor ve ekosistemimizdeki açık kaynak geliştiricilerini, açık kaynak geliştiricilerinin projelerine hizmet edecek, onları tanıtacak ve ihtiyaçlarını gözükür hale getirecek şekilde misyon kapsamımızı genişletiyoruz.

Bu noktada da atacağımız ilk adım elbette web sitemizi hem backend hem de frontend'de yenilemek olacak. Bu noktada herkesin katkısına açık, yine ekosistemdeki yazılımcıların öreceği bir yazılımı projelendirerek ilerlemeyi planlamaktayız.

Ben Figma üzerinden birkaç prototipleme ile çalışmalara başladım. Biz maddeleri toplayıp GitHub Projeler altında görebileceğiniz şekilde çalışma maddelerini belirlerken siz de çalışmada gönüllü olmak isterseniz bu "issue" kaydı altında gönüllülüğünüzü belirtirseniz projeye şimdiden katkıda bulunmuş olursunuz :)

**Comment by eserozvataf** [comment]
Figma'daki prototip çalışma'ya ait adres:

https://www.figma.com/file/BNVrH9KeyDUI7p3Zi1nBd1/Untitled?node-id=0%3A1

**Comment by sametaylak** [comment]
Yaay 🎉 🎉

**Comment by okandavut** [comment]
Biz zaten buradaydık abi her zaman :D

**Comment by berat** [comment]
Eğer yapabileceğim bir şey olacaksa seve seve. Beni de yazın :) (Kendime bu konuda fazla güvenmiyorum baştan belirteyim :) )

**Comment by ahmethelvaci** [comment]
Bugün Kodpod'da dinledim. Acikkaynak.info'yu biliyordum ama unutmuştum. Ben de frontend yada js ile katkıda bulunmak istiyorum. Yada başka konularda.

**Comment by tugsanunlu** [comment]
Ben de elimden geldiğince Front-End tarafında katkıda bulunmak isterim.

**Comment by kaangokdemir** [comment]
Frontend tarafında katkıda bulunmak isterim.

**Comment by hasaneksi97** [comment]
Bende elimden geldiğince yardımcı olurum .

**Comment by eserozvataf** [comment]
Hepinize teveccühünüz için çok teşekkürler :) Daha kolay bir geliştirme ortamı oluşturmak için ben de naçizane birkaç konfigurasyon yapmaya çalıştım.

acikkaynak.info'da yer alan kod tabanı [acikkaynak-website-old](https://github.com/acikkaynak/acikkaynak-website-old) üzerinde ve arşivlenmiş. Eski yapı tamamen GitHub üzerinden ilerliyordu ve bir backend'i yoktu.

Yeni yapı ise [acikkaynak-website](https://github.com/acikkaynak/acikkaynak-website) üzerinde ve [https://acikkaynak.herokuapp.com](https://acikkaynak.herokuapp.com) adresinde yayında. Bu yapı React Hooks ile yeniden yazılmaya başlandı ve [acikkaynak-api](https://github.com/acikkaynak/acikkaynak-api) adresindeki API ile haberleşecek.

Kod tabanına gönderilen PR ve commitler için şu anda Travis-CI üzerinden CI/CD pipeline çalıştırılıyor. [https://travis-ci.org/acikkaynak/acikkaynak-website](https://travis-ci.org/acikkaynak/acikkaynak-website), master branch'inde başarılı bir şekilde geçen buildler ise [https://acikkaynak.herokuapp.com](https://acikkaynak.herokuapp.com) adresini güncelliyor.

Sorularınız varsa buradan veya başka issue'lar üzerinden tartışabiliriz :)

...ya da... Telegram üzerinden haberleşmek için: https://t.me/acikkaynak

**Comment by Yutyo** [comment]
Yardımcı oluruz tabi abi.

**Comment by eserozvataf** [comment]
Yol Haritamızı ( #30 ) belirlediğimiz için artık projelendirmeyle ilgili maddemizi kapatabiliriz :)
