### ISSUE TITLE
Front-End / Backend

### ISSUE THREAD

**Issue by hasaneksi97** [acikkaynak/acikkaynak-website#21]
Çok iyi olduğum söylenemez ama tüm tecrübelerim ve çabam ile buradayım.

**Comment by okandavut** [comment]
Önemli olan birlikte bir şeyler yapmamız hoş geldin :)  @hasaneksi97

**Comment by eserozvataf** [comment]
Konuya #17 üzerinden devam ediyoruz zaten, bunu kapatıyorum :)
