### ISSUE TITLE
Web Sitesinde Yer Alan Eksik İçeriklerin Tamamlanması

### ISSUE THREAD

**Issue by eserozvataf** [acikkaynak/acikkaynak-website#35]

**Comment by tugsanunlu** [comment]
Lisanslar sayfası için planlanan bir çalışma var mıdır? 

Zamanında LKD'nin yaptığı lisans çevirileri var. Bunlardan faydalansak nasıl olur? 

http://ozgurlisanslar.org.tr

**Comment by AtakanErmis** [comment]
Lisanslar sayfası için choosealicense.com üzerindeki bilgileri Türkçeye çevirmeye başladım. Yakın zamanda bir PR açacağım.
