### ISSUE TITLE
Haberler Bölümü

### ISSUE THREAD

**Issue by eserozvataf** [acikkaynak/acikkaynak-website#36]

**Comment by sametaylak** [comment]
Eğer uygun ise bu tarafa yumulmak istiyorum. Herhangi bir tasarım mevcut mu? @eserozvataf

**Comment by eserozvataf** [comment]
Bir tasarım yok maalesef. En azından mekaniği örüp daha sonra bir tasarıma oturtabiliriz. Şu an üzerinde uğraşan birileri yok :)

**Comment by eserozvataf** [comment]
@sametaylak https://www.figma.com/file/gX92s4IGOX9ORqILUaYRtH/acik-kaynak-v1.0

adresine Haberler kısmıyla ilgili tasarım geldi :)

**Comment by sametaylak** [comment]
Tasarımda haber etiketleri ile ilgili bir şey göremedim. Filtreleme gibi bir durum yok gibi duruyor. @eserozvataf

**Comment by eserozvataf** [comment]
evet, aslında haberleri daha çok GitHub ile giriş yapan kişilerin acikkaynak.info'da sergilemek istedikleri projelerini seçtikten sonra onlar hakkında haber girebileceği bir mekanizma olarak düşünüyordum.

örnek: eserozvataf/darty'i ekledim.

daha sonra gelip bu repo'yu seçip "Darty 1.0 yayınlandı" diye haber girmek isteyebilirim. Haberler bölümünde de repo/proje ile ilgili haberler çıkar.
