### ISSUE TITLE
Backend API ile Web Sayfalarını Bağlamak

### ISSUE THREAD

**Issue by eserozvataf** [acikkaynak/acikkaynak-website#40]

**Comment by osmancansiz** [comment]
Nodejs & Express kütüphanesimi kullanılacak?

**Comment by eserozvataf** [comment]
https://github.com/acikkaynak/acikkaynak-api altında proje mevcut, halihazırda node.js üzerinde serverless kullanılıyor.

**Comment by osmancansiz** [comment]
Serverless konusunda tam olarak deneyimli değilim fakat bakacağım. Bana yapılması gereken olayları iletirseniz(galiba routes file'da olacak) bende ufak ufak bakmaya başlarım.
