### ISSUE TITLE
Türkiye Açık Kaynak Platformu Logo ve Bağlantısının Eklenmesi

### ISSUE THREAD

**Issue by eserozvataf** [acikkaynak/acikkaynak-website#41]
[Türkiye Açık Kaynak Platformu](https://www.turkiyeacikkaynakplatformu.com/) logo ve bağlantısı eklenecek.

**Comment by berat** [comment]
Nereye eklenecek? Tasarımda logoya ait bir yer göremedim.

**Comment by eserozvataf** [comment]
Evet maalesef henüz yerleştirmedik. UI/UX tarafında Figma tarafında güncelleme olmasını bekliyoruz. Olduğunda yine burayı güncellerim :)
