### ISSUE TITLE
Mobile genişliği ekranda navigasyon menüsünün sabitlenmesi

### ISSUE THREAD

**Issue by eserozvataf** [acikkaynak/acikkaynak-website#42]
Mobil genişliğine inildiğinde menü sayfa ile birlikte aşağı kayıyor ve beyaz bir alan görünmeye başlıyor. Menüyü sabitlersek sorun ortadan kalkacaktır.

![image](https://user-images.githubusercontent.com/866558/68085111-2bf6a780-fe4e-11e9-9e30-1f3ff53c070d.png)

**Comment by eserozvataf** [comment]
Menü sabitlendi, ancak menüden bir seçim yapıldığında menünün kapanması sağlanmalı.

**Comment by emrehayirci** [comment]
@eserozvataf Sanırım bu sorun çözüldü, sorunu gözlemleyemedim Chrome'da.

**Comment by eserozvataf** [comment]
Evet #44 ile birlikte çözüldü :) Test için teşekkürler. Issue'yu kapatıyorum.
