### ISSUE TITLE
Roboto Font Dosyaları Eklenmeli

### ISSUE THREAD

**Issue by MrPeker** [acikkaynak/acikkaynak-website#46]
Roboto font dosyaları eklenmeli sistemde Roboto olsa bile light (300) bulunan yerlerde eğer sistemde yoksa patlıyor. Google Fonts dışından font dosyaları dahil edilmeli.

`Privacy nedeniyle Google Fonts'dan font çekmemeye çalışıyoruz. Belki webpack bundling'in dışında bırakılarak daha güvenilir bir CDN'e taşınabilir zamanla.`

_Originally posted by @eserozvataf in https://github.com/acikkaynak/acikkaynak-website/pull/45#issuecomment-549315825_

**Comment by eserozvataf** [comment]
@MrPeker aslında şu anda Roboto embedded durumda, ancak width 400 için font dosyaları oluşturulmuş. Buna [google-webfonts-helper](https://google-webfonts-helper.herokuapp.com/) ile 300'ü de dahil edebiliriz. bu sorunu çözer sanırım?

Roboto'a ait CSS:
https://github.com/acikkaynak/acikkaynak-website/blob/development/src/app/layouts/default/assets/fonts/roboto.less

**Comment by MrPeker** [comment]
@eserozvataf evet çözer, görmemişim o dosyayı 😅
