### ISSUE TITLE
Font Awesome bağımlılığı kaldırılabilir.

### ISSUE THREAD

**Issue by numancan** [acikkaynak/acikkaynak-website#51]
Semantic UI, Font Awesome iconlarını içerdiği için kaldırılabilir olduğunu düşünüyorum. 

Kullanım farkı ise:
```
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';	
import { faClipboardList } from '@fortawesome/free-solid-svg-icons';

<FontAwesomeIcon icon={faClipboardList} />
```

```
import { Icon } from 'semantic-ui-react';

<Icon name="clipboard list" />
```
Kaldırılmaya karar verilir ise ben ilgilenebilirim.

**Comment by eserozvataf** [comment]
Merhaba,

Arada şöyle bir farklılık var, FontAwesome ile Semantic UI'ın sağladığı fontlar farklı render ediliyor. Semantic UI henüz FontAwesome'un eski sürümlerinde yer alan icon font'ları kullanıyor.

FontAwesome ise SVG kullanmaya başladı. Render mekaniklerinde farklılıklar olduğu için SVG şu and daha tercih edilir durumda.

Detaylar burada: https://css-tricks.com/icon-fonts-vs-svg/

Semantic UI bir süredir development'ına ara verdiği için henüz fontlarını SVG olarak servis etmiyor. Belki geri döndüklerinde SVG'e geçebilirler.

**Comment by numancan** [comment]
Anladım, çok teşekkür ederim.
