### ISSUE TITLE
Projeler Sliderı Responsive Değil

### ISSUE THREAD

**Issue by MrPeker** [acikkaynak/acikkaynak-website#56]
Projeler sliderı 1440 width den küçük cihazlarda özellikle mobilde oldukça kötü görünüyor

**Comment by eserozvataf** [comment]
Slider'ın scale olmakla ilgili bir sorunu da var, yükseklikten kırpıyor genelde.

**Comment by MrPeker** [comment]
Evet farkettim, sanırım farklı bir şekilde yaklaşmak gerekiyor height JS tarafından sabit bir şekilde tanımlanıyor, belki JS gerektirmeden çözülebilir. Ancak ilgilenecek zaman bulamadım. Mobilden de kötü görünmesi kötü hissettiriyor. CSS'ine güvenen ilgilenebilecek bir arkadaş var mı acaba?

**Comment by eserozvataf** [comment]
Şunu da yapabiliriz diye düşünüyorum,

Semantic UI 5 segment'e ayırıyor çözünürlükleri:
- mobile,
- tablet,
- computer,
- large screen,
- widescreen

mesela computer ve üstü çözünürlüklerde slider olur. diğerlerinde alt alta `<Card>`'lar şeklinde görünür. `<Responsive>` component'i ve `media selector`lar ile çözülebilir sanırım.

**Comment by MrPeker** [comment]
Bence güzel fikir, bu şekilde yapılmaması için de bir sebep göremiyorum, ne dersiniz?

**Comment by numancan** [comment]
Şöyle bir responsive denemesi yaptım ancak 500 width altında pek hoş durduğu söylenemez. @eserozvataf abinin fikrini uygulamak daha iyi olabilir.

![Carousel](https://user-images.githubusercontent.com/37977336/68337972-a0517500-00f2-11ea-8bed-3e1c7fd2c042.gif)

**Comment by MrPeker** [comment]
500 width altında genellikle mobil olacağını varsayarak buton şeklindeki kontrolleri kaldırıp kaydırarak kontrol etmelerini beklersek mobilde güzel durabilir bence

**Comment by numancan** [comment]
Teşekkür ederim. O zaman ben düzeltmeleri yapıp butonları kaldırıp PR göndereyim, duruma göre kullanır veya değiştiririz.

**Comment by MrPeker** [comment]
#57 ile çözüldü teşekkürler @numancan eline sağlık
