### ISSUE TITLE
React Profiler Desteği

### ISSUE THREAD

**Issue by eserozvataf** [acikkaynak/acikkaynak-website#61]
Development build için React Profiler'ın çalışıyor olması gerekmektedir.

![image](https://user-images.githubusercontent.com/866558/68792136-d1362a80-065b-11ea-9201-985660109bd9.png)

**Comment by emrehayirci** [comment]
Profiler dev için mevcut ve çalışıyor fakat production için istiyorsak: https://gist.github.com/bvaughn/25e6233aeb1b4f0cdb8d8366e54a3977

Kendi localimden çalıştığını gösteren bir görüntü:
<img width="1440" alt="Screen Shot 2019-11-13 at 20 16 49" src="https://user-images.githubusercontent.com/8329324/68796520-4d784000-0653-11ea-8fa2-7586a69daf2e.png">

**Comment by eserozvataf** [comment]
Teşekkürler @emrehayirci
