### ISSUE TITLE
Hakkımızda Bölümünün Başlığı

### ISSUE THREAD

**Issue by berkansasmaz** [acikkaynak/acikkaynak-website#64]
Normalde gözükmesi gereken = Açık Kaynak İnisiyatifi Hakkında
Kullanıcının gördüğü = Açık Kaynak İnisiyatifı Hakkında
İnsiyatifi kısmında ki 'i' karakterinin 'f' harfinden dolayı 'ı' gibi gözükmesinden dolayı oluşan hata.

**Comment by Ardakilic** [comment]
Kullanılan Roboto fontunun ligature'undan dolayı bu.

Aslında şu pull request'e göre bu sorunun Türkçe'de olmaması lazım: https://github.com/google/roboto/pull/193

Ayrıca ilgili bir diğer issue da burada: https://github.com/google/roboto/issues/115
