### ISSUE TITLE
Projelerin Detaylarının Eklenmesi

### ISSUE THREAD

**Issue by cagandev** [acikkaynak/acikkaynak-website#70]
Projelerin eklenme aşamasında her bir projenin içerisinde kullanılan teknolojiler ve/veya programlama dilleri eklenirse daha iyi dönüşümler alınacağına inanıyorum. Bu sayede yardımcı olmak isteyen kişiler daha rahat bir şekilde destek vereceği projeyi seçebilir. İyi çalışmalar.

[https://acik-kaynak.org/lists/projects/](projects)

**Comment by eserozvataf** [comment]
Gayet yerinde bir öneri. İş planımıza alalım :)
