### ISSUE TITLE
GitHub ile Giriş: Geniş Yetkiler İsteniyor

### ISSUE THREAD

**Issue by MrPeker** [acikkaynak/acikkaynak-website#75]
Public repositoryler ve kişisel (ve gizli) verilere okuma ve **yazma izni** isteniyor.

- Private email addresses
- Private profile information
- write all public repository data
- write all user data

bunlar sıkıntılı maddeler/izinler olarak gözüme çarptı, eğer platform işleyişine bir engel oluşturmayacaksa read-only e çevrilmeli ve private email & profile info nun da istenmemesi gerektiğini düşünüyorum. Private email & profile info direkt istenmiyor, ancak full profil erişimi istendiğinden dolayı bunlara da erişim sağlanacağından dolayı GitHub uyarıyor.

![image](https://user-images.githubusercontent.com/23459375/76712303-7a834f00-6728-11ea-8ef6-8d2c5a543ec5.png)

**Comment by eserozvataf** [comment]
Write istemek abes evet, private e-mail address de gerekli mi bilmiyorum belki kullanıcı match etmek için gerekebilir. Diğerlerine ise bakalım, stats için neleri kullanacağız ona göre azaltılır.
