### ISSUE TITLE
GNOME Toplulukla Etkileşim Yarışması'nın Duyurulması ve Tartışılması

### ISSUE THREAD

**Issue by velitasali** [acikkaynak/acikkaynak-website#79]
GNOME Foundation ve EndlessOS'in birlikte yürüttüğü, orijinal adıyla "Community Engagement Challenge" veya Türkçe kabaca "Toplulukla Etkileşim Yarışması", azınlık veya 3. Dünya ülkerinden yazılım dünyasına yeni giriş yapmış insanların açık kaynak topluluğuna teşvikinin sağlanmasını amaçlayan bir yarışmadır.  Yarışma dahilinde katılımcılardan bireysel veya grup halinde bunu mümkün kılacak projelerini ilk aşamada taslak olarak sunmaları isteniyor ve daha sonra uygun görülürse, sundukları projelerin mümkün olmasını sağlayabilecek yardımın yapılması ve en sonunda yarışmayı kazananlara para ödülü verilmesi hedefleniyor.  

**Bu hata kaydı şunlara karar vermek için oluşturulmuştur:**
* Pull request ile oluşturulacak acik-kaynak.org sayfasının ve varsa diğer değişikliklerin nasıl olması gerektiğine karar verilmesi veya o yönde köprü olarak kullanılması
* Fikirlerin ortaya atılması ve tartışılması
* Grupların belirlenmesi uygun tartışma ortamının oluşturulması
* Taslakların yollanması

**Neyi hedefler?**
* İnsanların haberdar edilmesi
* Topluluk ile beraber katılımın sağlanması 
* Birlikte çalışmanın sağlanması ve Türkiye'deki FOSS topluluğunun güçlendirilmesi
* GNOME gibi kabül görmüş vakıflarla bağların güçlendirilmesi

**Önemli notlar**
Son başvuru tarihi 1 Temmuz'dur.

## Yarışma detayları

Yarışma detaylarının yerelleştirilmiş sürümü 
https://github.com/challenge-tr/taslak-proje.

Yarışma resmi sitesi (İngilizce)
http://gnome.org/challenge

Yarışma hakkında sıkça sorulan sorular (İngilizce)
http://gnome.org/challenge/faq

Projeler Slack üzerinde tarşılacak: 
https://join.slack.com/t/challengetr/shared_invite/zt-eeq9zqte-Qu09NZAZY9QsRJ61aMp5dQ

Proje fikirlerinizi burada belirterek tartışmaya açabilirsiniz.  

## Projeler

1. Açık Üniverstite: https://github.com/challenge-tr/proje-acik-universite/ (başvuru yollandı)

**Comment by velitasali** [comment]
*bu girdi yarışma detayların yerelleştirilmiş sürümü ile değiştirilecek*

**Comment by velitasali** [comment]
@eserozvataf hocam yarışma detaylarını daha anlaşılabilir olması açısından şöyle yerelleştirdim https://github.com/velitasali/gnome-community-engagement-challange-taslak-proje. 

Yarışmaya katılım için her grupta (eğer birden fazla olursa) en az bir kişinin İngilizce biliyor olması yeterli olur diye düşünüyorum. 

https://www.gnome.org/challenge/promote/ adresinde posterler mevcut. 

Oluşturduğum https://github.com/velitasali/gnome-community-engagement-challange-taslak-proje deposunda, grupların (yine, birden fazla olursa diye) başvurudaki her bir soruyu dosya haline getirip birden fazla kişinin düzenlemesine yardımcı olur diye oluşturmuştum. Hem bu sayede başkalarının görmesi ve iç içe geçmiş olarak çalışmak kolay olur diye.

**Comment by hwpplayer1** [comment]
> GNOME Foundation ve EndlessOS'in birlikte yürüttüğü, orijinal adıyla "Community Engagement Challenge" veya Türkçe kabaca "Toplulukla Etkileşim Yarışması", azınlık veya 3. Dünya ülkerinden yazılım dünyasına yeni giriş yapmış insanların açık kaynak topluluğuna teşvikinin sağlanmasını amaçlayan bir yarışmadır. Yarışma dahilinde katılımcılardan bireysel veya grup halinde bunu mümkün kılacak projelerini ilk aşamada taslak olarak sunmaları isteniyor ve daha sonra uygun görülürse, sundukları projelerin mümkün olmasını sağlayabilecek yardımın yapılması ve en sonunda yarışmayı kazananlara para ödülü verilmesi hedefleniyor.
> 
> **Bu hata kaydı şunlara karar vermek için oluşturulmuştur:**
> 
>     * Pull request ile oluşturulacak acik-kaynak.org sayfasının ve varsa diğer değişikliklerin nasıl olması gerektiğine karar verilmesi veya o yönde köprü olarak kullanılması
> 
>     * Fikirlerin ortaya atılması ve tartışılması
> 
>     * Grupların belirlenmesi uygun tartışma ortamının oluşturulması
> 
>     * Taslakların yollanması
> 
> 
> **Neyi hedefler?**
> 
>     * İnsanların haberdar edilmesi
> 
>     * Topluluk ile beraber katılımın sağlanması
> 
>     * Birlikte çalışmanın sağlanması ve Türkiye'deki FOSS topluluğunun güçlendirilmesi
> 
>     * GNOME gibi kabül görmüş vakıflarla bağların güçlendirilmesi
> 
> 
> **Önemli notlar**
> Son başvuru tarihi 1 Haziran'dır.
> 
> Yarışma resmi sitesi (İngilizce)
> http://gnome.org/challenge
> 
> Yarışma hakkında sıkça sorulan sorular (İngilizce)
> http://gnome.org/challenge/faq
"acik-kaynak.org sayfasının" ve Github organizasyonunun olması zaten üzerinde anlaştığımız bir konu. Fikir olarak ben hem bilgisayarda yerel olarak hem de sunucudan veri çekecek extensions.gnome.org üzerinde ve Github'da barındırılabilecek kabul edilebilir lisansı olan bir GNOME eklentisi düşünüyorum. Hangi konuda sıkıntı çektiğimi detaylı olarak iletişim kanalarında anlatabilirim kısa bir inceleme yapmam lazım. Ama sürüm farkı sebebiyle oluşan uyumsuzlukları örnek gösterebilirim. Çok fazla grup açmak yerine önceliği bir gruba vermekten yanayım. Sonra bu grubun alt grupları açılabilir bence. Taslakların yollanması konusunda tecrübem yok maalesef bu konuyu gruptan öğreneceğim. Şu an için belirtmek istediklerim bunlar iletişim kanalları üzerinden bilgi aldıkça güncellemeyi düşünüyorum bu konudaki yorumumu. Teşekkürler.

**Comment by velitasali** [comment]
> Fikir olarak ben hem bilgisayarda yerel olarak hem de sunucudan veri çekecek extensions.gnome.org üzerinde ve Github'da barındırılabilecek kabul edilebilir lisansı olan bir GNOME eklentisi düşünüyorum

@hwpplayer1 "Açık Kaynak İnisiyatafi" nin  eklenti sürümünün olmasından bahsediyorsunuz galiba. Tam olarak anlamadım. Biraz daha bilgi verir misiniz bu konuda?

> Taslakların yollanması konusunda tecrübem yok maalesef bu konuyu gruptan öğreneceğim.

Proje taslağını aslında sadece kendi aramızda daha anlaşılabilir olması açısından iyi olur demiştim. Yani taslak asıl başvuru sırasında gerekmiyor. **Asıl** başvuru https://www.gnome.org/challenge/ adresindeki _Submit your proposal_ butonu tıklandıktan sonra açılan form doldurularak yapılmakta ve bu forma kullanıcı adı ve şifre konulduktan sonra yarıda bırakılıp ve yine aynı bilgiler kullanılarak devam edilebilmekte.

**Comment by hwpplayer1** [comment]
@velitasali Evet zaten projenin kaynağı burası ve ortaya çıkacak ürün de buradaki katkıcıların oluyor Özgür olduğu için biliyorsunuz. Ben yaşadığım sorunları anlatmak istedim. GNOME üzerindeki eklentilerin devam ettirilmemesi bakımının yapılmaması gibi bir durumla karşılaşmamak istiyorum. Bunu anlatmaya çalıştım. 

Proje taslağı için aklıma gelen kodun veya içeriğin branchler ile sistematik hale getirilmesi. Siz daha iyi bilirsiniz ancak test edip de son halini göndereceğimizi düşünüyorum.

Eksik bilgi vermişsem düzeltebilirseniz sevinirim. Teşekkürler

**Comment by velitasali** [comment]
@hwpplayer1 Dediğiniz gibi GNOME eklentilerinin, GNOME'un sonraki sürümlerinde çalışmayı durdurduğu veya düzgün çalışmadığı bir gerçek. Proje fikriniz dahilinde bu sorunu mu çözmek istiyorsunuz? 

> Proje taslağı için aklıma gelen kodun veya içeriğin branchler ile sistematik hale getirilmesi. Siz daha iyi bilirsiniz ancak test edip de son halini göndereceğimizi düşünüyorum.

Bu kısmı tam olarak anladım ancak şöyle yapabiliriz. Siz yarışma dahilinde anlamadığınız yerleri sorun, ben de o kısımları değişteriyim. Zaten oluşturduktan sonra pek fazla inceleme fırsatım olmadı.

**Comment by hwpplayer1** [comment]
@velitasali Evet hangi alanda sıkıntı çekiyorsam orada çözüm arıyorum genellikle. Proje fikrimin kritik kısmı burası. 

Tamam test etmekten kastettiğim sunulacak işin GNOME'a ulaşmadan önce hazır olması idi. Genel olarak böyle bir kaygım olduğu için ve geliştirme sürecinin devam edeceğini umduğum için test kavramını andım.

Teşekkürler

**Comment by velitasali** [comment]
> @velitasali Evet hangi alanda sıkıntı çekiyorsam orada çözüm arıyorum genellikle. Proje fikrimin kritik kısmı burası.

Anladım. Fikriniz yarışmanın ana hedefi olan `"Hedefimiz bireyleri veya takımları, sonraki nesil geliştiricileri FOSS topluluğu ile bağlayacak ve gelecek yıllarda öyle kalmalarını sağlayacak harekete geçirici fikirlerini paylaşmaya teşvik etmektir."` hedefine ulaştığı sürece uygundur ve düşünülebilir.
 
> Tamam test etmekten kastettiğim sunulacak işin GNOME'a ulaşmadan önce hazır olması idi. Genel olarak böyle bir kaygım olduğu için ve geliştirme sürecinin devam edeceğini umduğum için test kavramını andım.

Aynen şu anda tümüyle idrak edilmiş bir proje fikri yok ortada. Önceki yorumlarınızda belirttiğiniz gibi birden reponun kullanılıyor olması kafa karışıklığı yaratabilir. Sanırım diğer repoların issues sekmelerini devre dışı bırakmak doğru bir tercih olabilir.

**Comment by hwpplayer1** [comment]
@velitasali Evet fikirlerimiz uyuşuyor. Sistem programlama esas ilgi alanım olduğu için örneğin htop gibi bir yazılımın devamı niteliğinde bir eklenti olabilir. Araştırdığımda Red Hat 8.2 mağazası üzerinde bu eklentiyi göremedim. Bu ve benzeri bir sistem yazılımının yansıması olabilir hem yerelde hem sunucudan veri çekecek şekilde ayarlanmasıyla. Ancak daha derine inmemiz şu an konumuzun dışına çıkar offtopic olur. Belki ileride FOSS dayanışması açısından proje büyütülebilir.

Teşekkürler

**Comment by velitasali** [comment]
@hwpplayer1 anladım hocam. Bu yarışmanın hedefinin dışında kalıyor olsa da üzerinde birlikte çalışabilir diyorsunuz doğru mu anladım? Eğer öyleyse, ben de destek olabilirim. 

Onun haricinde, ilk mesajınızda > dan sonra iki satır bırakırsanız mesajınız alıntı olarak gözükmeyecektir. Teşekkürler.

**Comment by hwpplayer1** [comment]
@velitasali bey evet detay vermem gerekirse htop bir eklenti olarak ilk planda projemizin dikkate alabileceği bir yazılım olabilir. Ancak htop gibi bir sistem yazılımı az önce adını anamadım şimdi anayım : [System Monitor](https://extensions.gnome.org/extension/120/system-monitor/) gibi bir eklenti sadece eklenti değil bir "sistem arayüzü" bu sebeple daha kapsamlı derinlemesine konuştuğumuzda iş GNOME'dan çıkıp GNU/Linux alanına kayacak. Bunu da FOSS ile dayanışma kapsamında uzun süreli inceleyebiliriz. Şimdi alıntı yapmadım ama anladım. Teşekkürler

**Comment by velitasali** [comment]
Slack üzerinden projelerin tartışması yapılacaktır ve tartışmanın sadece buradan devam etmesi için "genel" kanalını salt-okunur yaptım. Proje fikirleri için ayrı kanallar eklenebilir.

Ana gönderiye şu bilgiler eklendi:

> Projeler Slack üzerinde tarşılacak:
> https://join.slack.com/t/challengetr/shared_invite/zt-eeq9zqte-Qu09NZAZY9QsRJ61aMp5dQ
> 
> Proje fikirlerinizi burada belirterek tartışmaya açabilirsiniz.

**Comment by uguravci-0** [comment]
öncelikle merhabalar bu Slack ne işe yarıyor ve hangi konuda tartışıcaz
bu arada web siteye kaydımı oluşturdum

Veli Tasalı <notifications@github.com>, 25 May 2020 Pzt, 16:50 tarihinde
şunu yazdı:

**Comment by velitasali** [comment]
hoşgeldiniz @uguravci-0. 

Slack, proje fikirlerinin gruplandırılması ve tartışılması için kullanılmaktadır. Fikirlerin haricindeki tartışmalar buradan devam edecektir.

**Comment by velitasali** [comment]
@uguravci-0 ayrıca bir proje fikriniz varsa tartışabiliriz. Proje fikrinizin uygunluğunu ilk gönderide belirtilen yarışma detayları linklerini kullanarak öğrenebilirsiniz.

Katılacak bir proje arıyorsanız. Yine ilk gönderide belirtilmiş projelerin slack kanallarını ziyaret edin derim.

**Comment by hwpplayer1** [comment]
Projenin gelişimi göz önüne alındığında, farklı bir yol haritası belirlenmesi ihtiyacına paralel olarak projeden ayrıldığımı, ve tekrar iletişim kurulmasını reddettiğimi tüm kamuoyuna belirtirim. 

Considering the development of the project, I would like to inform the public that I left the project in line with the need to define a different roadmap and that I refuse to be contacted again.

**Comment by velitasali** [comment]
Bunu duyduğuma üzüldüm hocam. Keşke önceden haber etseydiniz, tartışırdık üzerinde.  

"_farklı bir yol haritası belirlenmesi ihtiyacına paralel olarak projeden ayrıldığımı_" kısmını tam anlamadım ancak iletişim kurulmasını istemediğinizi belirtmişsiniz.
